<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXKxmBNZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXKxmBNZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXKxmBNZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXKxmBNZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXKxmBNZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XKxmBNZ',
    'container.build_id' => 'd82ed867',
    'container.build_time' => 1603723532,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXKxmBNZ');
